### ISSUE TITLE
Apache POI vulnerability

### ISSUE THREAD

**Issue by dschwalm** [concordion/concordion-excel-extension#14]
Hi,

As all Apache POI versions prior to 3.15 contains a serious vulnerability, the POI should be upgraded to at least 3.15, but preferably to 3.17.

https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-22766/Apache-POI.html

3.17 POI contains breaking changes though, getBoldweight() method has been removed from org.apache.poi.ss.usermodel.Font.

Any plans to do the upgrade?

PRs are welcome?

Thanks,
Daniel

**Comment by robmoffat** [comment]
A PR would be very welcome!

**Comment by wilczelyko** [comment]
I have just created pull request with POI upgrade

**Comment by dschwalm** [comment]
I just waited because of the tests failed and did not have time to figure out how to fix them. I see that you did not update the tests neither, correct?

**Comment by wilczelyko** [comment]
Nope, I haven't. Tests fails in my machine because of locale - comma or dot 
as floating separator. Is that what you mean?
Adam

W 16 września 2019 14:28:12 dschwalm <notifications@github.com> napisał:

**Comment by dschwalm** [comment]
Yes, that is what I mean. 
I am not sure whether the test results should depend on the locale of the machine executes the tests. My gut feeling is no.
But for changing that we may need to review these tests carefully.

**Comment by robmoffat** [comment]
Fixed by @dschwalm with https://github.com/concordion/concordion-excel-extension/pull/17

**Comment by robmoffat** [comment]
Version 2.1.2 now available on maven central
