### ISSUE TITLE
exceptions during html translation should include location in the excel source

### ISSUE THREAD

**Issue by vgheo** [concordion/concordion-excel-extension#15]
In the current implementation, an error occurs during translation from excel to html/concordion occurs an exception is thrown and displayed to the user as diagnosis.

As the text does not contain any hint to the location of the source of the error, it makes it very difficult do diagnose.

Suggest to include the excel location of the cell being processed with the exception.

**Comment by robmoffat** [comment]
This makes perfect sense to me.  I think one way to achieve this would be for the BasicCellConversionStrategy to output row, column and sheet into a HTML attribute in the output HTML. Any exception generated could then refer to this.  

I'll be able to help with this over the next week if you want, but I am very out-of-touch with this codebase now, so a PR would be preferable.
