### ISSUE TITLE
Possibility to hide intermediary calculations

### ISSUE THREAD

**Issue by GoGoris** [concordion/concordion-excel-extension#6]
Hi, we have excel specifications for calculations. Is it possible to hide columns with intermediary calculations in the excel, so that they won't be shown in the final concordion tests? Now we have to keep a separate excel with formulas and then copy the results to another excel for concordion. It is not urgent (I know you're busy with concordion 2.0 at the moment) but it would be a nice feature.

Kind regards

**Comment by robmoffat** [comment]
I tried to replicate your issue, but couldn't:

From ExcelConcordionTutorial.xlsx, I hid column B, and ran the test again, but it all worked fine. 

Admittedly, this was from the 2.0-SNAPSHOT build, but none of the Excel code has changed between releases so I think I must be doing something wrong in trying to re-create your bug? 

[ExcelConcordionTutorial.xlsx](https://github.com/concordion/concordion-excel-extension/files/151572/ExcelConcordionTutorial.xlsx)

cheers,

Rob

**Comment by GoGoris** [comment]
Sorry I wasn't clear enough. The tests still work fine, but we want to make the columns invisible in the result html of the concordion test. Sometimes we also use a seperate sheet, but they are also visible in the result because they are used to create different tests.

**Comment by robmoffat** [comment]
FYI, I started working on this yesterday, but it seems there is a problem with either the poi api or my OSX excel in that it doesn't report columns being hidden properly.   Rows can be hidden ok but not columns it seems.

Will take a closer look tonight

**Comment by GoGoris** [comment]
Maybe Libreoffice helps? There I am also able to hide columns the same way like in Excel. https://www.libreoffice.org/download/libreoffice-fresh/

**Comment by robmoffat** [comment]
HI Stephen,

I've just released a new 2.0.0-SNAPSHOT version of the Excel plugin, to:

http://oss.jfrog.org/artifactory/simple/oss-snapshot-local/

I believe it fixes your problem.  There is a [test](https://github.com/concordion/concordion-excel-extension/blob/master/src/test/resources/org/concordion/ext/excel/HiddenColumn.xlsx)  which demonstrates this functionality.  

Let me know if this fixes it.

cheers,

Rob

**Comment by GoGoris** [comment]
Thanks! I will look test this when I have time.

**Comment by robmoffat** [comment]
Now released at version 2.0.0, compatible with concordion 2.0.0

cheers,

Rob
