### ISSUE TITLE
Libreoffice problem

### ISSUE THREAD

**Issue by igorcouto** [concordion/concordion-excel-extension#7]
Hi, 

I'm getting this error when exporting from libreoffice:

org.concordion.ext.excel.ExcelConversionException: Trying to add content above the HTML root element

**Comment by robmoffat** [comment]
HI igorcouto,

I'm not familiar with Libreoffice... I assume you are using it to create an Excel format file for concordion to use.  Do you have an example we can look at that exhibits this problem?  

I am expecting this is causing a problem with POI (which is used for loading the Excel file).  So, you might find your answer in the POI mailing lists too.
