### ISSUE TITLE
FOR NULL EXCEL CELL  NUll POINT ERROR

### ISSUE THREAD

**Issue by yangjiebeijing** [concordion/concordion-excel-extension#8]
org.concordion.ext.excel.conversion.cellcontent.DefaultStyleConverter

....
@Override
	public void process(Cell c, HTMLBuilder b) {
		StringBuilder out = new StringBuilder();
		extractColourStyle(c, out);
		extractFontStyle(c, out);
		handleHiddenCells(c, out);
		if (out.length() > 0) {
			b.addAttribute("style", out.toString());
		}
	}
....
**please,add  like this**
protected void handleHiddenCells(Cell c, StringBuilder out) {
		**if (c == null) {
			return;
		}**
		if (isHiddenRow(c) || isHiddenColumn(c)) {
			out.append("display: none; ");
		}
	}

**Comment by robmoffat** [comment]
This is fixed in release 2.0.2
thanks for reporting.
