### ISSUE TITLE
Possibility to hide pages

### ISSUE THREAD

**Issue by GoGoris** [concordion/concordion-excel-extension#9]
Hi, to follow up on #6: Could you also make it possible to hide a page in excel from the HTML output? This would be very handy in cases where we use autocompletion or where we have calculations that demand for a different table.

You help is very much appreciated!

**Comment by robmoffat** [comment]
How do you think this should work, Stephen?

I notice there is a "Hide" function for sheets in my copy of Excel - I am thinking that hiding sheets from the output that are hidden this way in Excel would be the best approach?

**Comment by robmoffat** [comment]
This is now fixed.  Hide the page in Excel and it hides in C-E-E output too.
Released in 2.0.2

**Comment by GoGoris** [comment]
Thank you for the quick fix!
